name: tasmota_plug_control
description: "A simple controller for tasmota smart plugs."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_native_splash: ^2.4.0 todo
  heart: ^0.1.3
  http: ^1.2.1
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "icon.png"
  android: true
  ios: true
  linux: true

  min_sdk_android: 16
  adaptive_icon_background: #ffffff
  adaptive_icon_foreground: "icon_outline.png"
  remove_alpha_ios: true